[package]
name = "henrything"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
hyper = "0.12"
log = "0.4"
pretty_env_logger = "0.3"
